#!/bin/bash
echo -n "Sisesta enda vanus: "
read vanus
if test $vanus -gt 0 -a $vanus -lt 11
then
echo "Sa oled laps"
elif test $vanus -ge 11 -a $vanus -lt 18
then
echo "Sa oled nooruk"
elif test $vanus -ge 18 -a $vanus -lt 65
then
echo "sa oled täiskäsvanud"
elif test $vanus -ge 65
then
echo "sa oled senjoor"
else
echo "Arv on vigane"
fi
